Insert into maps values(1, 'QA Instancing Playfield');
Insert into maps values(10, 'Leifs testplayfield');
Insert into maps values(100, 'Field of the Dead_Rivers');
Insert into maps values(1000, 'Conarch Village');
Insert into maps values(10003, 'BLG_CLONE_2');
Insert into maps values(1001, 'Spider_Caverns');
Insert into maps values(1002, 'Venomfall Caves');
Insert into maps values(1003, 'Blue Iron Mine');
Insert into maps values(1004, 'Spider Cavern');
Insert into maps values(1006, 'Bear_Cave');
Insert into maps values(101, 'Stresstest playfield');
Insert into maps values(1010, 'Conall''s Valley');
Insert into maps values(1012, 'Conall`s Valley DX10 Continued');
Insert into maps values(102, 'Acheronian Temple Lava tech');
Insert into maps values(1020, 'Field of the Dead');
Insert into maps values(1022, 'Kyllikki''s Crypt');
Insert into maps values(1024, 'Toirdealbach''s Tomb');
Insert into maps values(1025, 'Field of the Dead SkyDome');
Insert into maps values(103, 'Frost Swamp Group - Master Region XXX');
Insert into maps values(1030, 'Murrogh_Forest');
Insert into maps values(104, 'backdrops');
Insert into maps values(1040, 'Lacheish Plains ');
Insert into maps values(1041, 'Lacheish Plains PvP');
Insert into maps values(1042, 'Frost Swamp - Master Region');
Insert into maps values(1044, 'Fight Club Arena');
Insert into maps values(1045, 'Field of Chiefs');
Insert into maps values(1051, 'Cave of Coltranach');
Insert into maps values(1052, 'Yakhmar''s Cave');
Insert into maps values(1053, 'Small_Eiglophian_Cave');
Insert into maps values(1054, 'Cannibal Cave');
Insert into maps values(1055, 'cannibal_caves II');
Insert into maps values(1056, 'Eiglophian Mountains New4');
Insert into maps values(1057, 'Ice Cave');
Insert into maps values(10600, 'ACG01 Outdoor Aquilonia');
Insert into maps values(1080, 'Atzel''s Approach');
Insert into maps values(10800, 'White Sands');
Insert into maps values(10803, 'White Sands');
Insert into maps values(10805, 'White Sands');
Insert into maps values(10810, 'Isle of the White Sands Master Playfield');
Insert into maps values(1082, 'Halls of Eternal Frost');
Insert into maps values(1084, 'The Dragon''s Lair');
Insert into maps values(1085, 'Atzel''s Fortress');
Insert into maps values(1090, 'Ymir''s Pass');
Insert into maps values(1091, 'Ymirs Pass Mobs');
Insert into maps values(1092, 'Spider_Queen_dungeon');
Insert into maps values(1093, 'Temple_of_Ymir');
Insert into maps values(1100, 'venarium');
Insert into maps values(11040, 'Border Kingdoms, Cimmerian End');
Insert into maps values(12003, 'Test_Buggy_rockside');
Insert into maps values(12070, 'Border Kingdoms, Aquilonian End');
Insert into maps values(1211, 'Frost Swamp I');
Insert into maps values(1212, 'Frost Swamp II');
Insert into maps values(1213, 'Frost Swamp Group - Master Region');
Insert into maps values(1214, 'Frost Swamp');
Insert into maps values(1217, 'Frost Swamp - May Marketing');
Insert into maps values(13050, 'Border to Kush');
Insert into maps values(14, 'STATELS FOR POLISH');
Insert into maps values(15, 'markus playground');
Insert into maps values(17, 'Small Drooling Beaverzzz');
Insert into maps values(18, 'ulfk');
Insert into maps values(19, 'Ghost Palace');
Insert into maps values(2, 'QA Test Playfield');
Insert into maps values(2000, 'Old Tarantia');
Insert into maps values(2001, 'Tarantia Master Region');
Insert into maps values(2002, 'Old Tarantia Statels and Hmaps');
Insert into maps values(2003, 'Sailors Den');
Insert into maps values(2004, 'The Green Man Tavern');
Insert into maps values(2005, 'Kalanthe''s Hideout');
Insert into maps values(20095, 'Cloned playground for PF test');
Insert into maps values(2010, 'Tarantia Noble District');
Insert into maps values(2011, 'Armsman''s Tavern');
Insert into maps values(2012, 'Tarantia Noble District Statels and Hmaps');
Insert into maps values(2013, 'Accountant''s Office');
Insert into maps values(2018, 'Barefoot Maiden''s Inn');
Insert into maps values(2019, 'Armsman''s Arena');
Insert into maps values(2020, 'Tarantia Common District');
Insert into maps values(2022, 'Capiton`s House');
Insert into maps values(2023, 'Artani Troka''s Safe House');
Insert into maps values(2024, 'Caecilia''s Warehouse');
Insert into maps values(2025, 'Sevilin''s Thugs');
Insert into maps values(2026, 'Outflow Tunnels');
Insert into maps values(2030, 'The Cistern');
Insert into maps values(2032, 'The Main System');
Insert into maps values(2033, 'The Catacombs');
Insert into maps values(2040, 'Castle of King Conan');
Insert into maps values(2050, 'Bossonian_Marches 06-09-2006');
Insert into maps values(2052, 'Bossonian_Marches 17-01-2006');
Insert into maps values(20603, 'Test Playfield');
Insert into maps values(2070, 'Poitain');
Insert into maps values(2071, 'Imirian Ravine - Master Region');
Insert into maps values(2080, 'Wild Lands of Zelata');
Insert into maps values(2081, 'Cave of Zelata');
Insert into maps values(2082, 'The Maze');
Insert into maps values(2083, 'Stillwater Gorge');
Insert into maps values(2084, 'Border Range');
Insert into maps values(2085, 'Sanctum of the Burning Souls');
Insert into maps values(2086, 'Deadwood Ravine');
Insert into maps values(2087, 'The Old Smuggler Route');
Insert into maps values(2088, 'The Old Smuggler Route');
Insert into maps values(2090, 'Thunder River');
Insert into maps values(2093, 'Blood Rite Subterrain');
Insert into maps values(2101, 'Motherplayfield Villa Amiel');
Insert into maps values(2102, 'Motherplayfield Villa Verde');
Insert into maps values(21021, 'E3 Video SHADOWPLAYFIELD');
Insert into maps values(2103, 'Motherplayfield Villa Lentulus');
Insert into maps values(2104, 'Motherplayfield Villa Camillus');
Insert into maps values(2105, 'Motherplayfield Villa Paetus');
Insert into maps values(2111, 'Villa Amiel');
Insert into maps values(2112, 'Villa Amiel II');
Insert into maps values(2121, 'Villa Verde');
Insert into maps values(2131, 'Villa Lentulus');
Insert into maps values(2141, 'Villa Camillus');
Insert into maps values(2151, 'Villa Paetus');
Insert into maps values(22, 'Viljar');
Insert into maps values(22000, 'Shadow Tarantia');
Insert into maps values(22001, 'Shadow Tarantia Idar');
Insert into maps values(2201, 'Imirian Ravine I');
Insert into maps values(2202, 'Imirian Ravine II');
Insert into maps values(2203, 'Imirian Ravine Group - Master Region');
Insert into maps values(2205, 'Imirian Ravine');
Insert into maps values(23666, 'Shadow Tarantia AI2');
Insert into maps values(24020, 'ShadowTortage');
Insert into maps values(24021, 'Murrogh_Forest_JasonTESTrename head');
Insert into maps values(24023, 'ShadowTortage Andreas');
Insert into maps values(24024, 'Tortage Town campaths andreaso');
Insert into maps values(29, 'Joehs Playground 1');
Insert into maps values(3, 'object sound test');
Insert into maps values(30, 'Joehs Playfield - The End Battle Second Iteration Test');
Insert into maps values(3000, 'Khemi');
Insert into maps values(30000, 'Backup Khemi');
Insert into maps values(3001, 'Black Castle');
Insert into maps values(3002, 'Serpent''s Head Inn Room 3');
Insert into maps values(3003, 'Serpent''s Head Inn');
Insert into maps values(3004, 'Serpent''s Head Inn Room 7');
Insert into maps values(3006, 'Purple Carp Tavern');
Insert into maps values(3007, 'Serpent''s Head Inn Room 7');
Insert into maps values(3009, 'Mage Study');
Insert into maps values(3010, 'Siptah''s Isle');
Insert into maps values(3012, 'Khemi WIP');
Insert into maps values(3020, 'Khopshef Province');
Insert into maps values(3022, 'Treasury of the Ancients');
Insert into maps values(3023, 'Khopshef Province - Ghostpalace');
Insert into maps values(3024, 'Pyramid of the Ancients');
Insert into maps values(3025, 'Bubshur House');
Insert into maps values(3026, 'Blessed Caves');
Insert into maps values(3029, 'Black Ring Citadel E3');
Insert into maps values(3029, 'PVP Lobby');
Insert into maps values(303, 'QA My sanctuary summervacation place');
Insert into maps values(3030, 'Kheshatta');
Insert into maps values(3031, 'The Onyx Chambers');
Insert into maps values(3032, 'Thoth-Amons Stronghold');
Insert into maps values(3033, 'Caravan Raider''s Hideout');
Insert into maps values(3034, 'Black Ring Citadel Wing 1');
Insert into maps values(3035, 'The Scorpion Cave');
Insert into maps values(3036, 'Tuthnemtip Estate');
Insert into maps values(3037, 'Setsokhaten''s Crypt');
Insert into maps values(3039, 'The Soul Chamber');
Insert into maps values(3040, 'Ruins of Khet 6-1-2006');
Insert into maps values(3041, 'Khopshef Paint Error');
Insert into maps values(3042, 'TESTINggg');
Insert into maps values(3044, 'Black Ring Citadel Wing 2');
Insert into maps values(3045, 'Black Ring Citadel');
Insert into maps values(3046, 'Thoth-Amons Tower');
Insert into maps values(3047, 'Den of Perversions');
Insert into maps values(3048, 'Apprentice Quarters');
Insert into maps values(3050, 'Purple Lotus Swamp');
Insert into maps values(3051, 'Oasis of Zaara - Master Region');
Insert into maps values(3065, 'Tarantia');
Insert into maps values(3066, 'Tarantia E3 06');
Insert into maps values(308, 'QA CG CG CG CG');
Insert into maps values(312, 'Jorgen''s Test Playfield');
Insert into maps values(313, 'Sanctum of the Burning Souls - jorgend');
Insert into maps values(32, 'Mats Tveita');
Insert into maps values(320, 'Conall''s Valley - Senses Test');
Insert into maps values(3201, 'Oasis of Zaara I');
Insert into maps values(3202, 'Oasis of Zaara II');
Insert into maps values(3203, 'Oasis of Zaara Group- Master Region');
Insert into maps values(3204, 'Oasis of Zaara');
Insert into maps values(326, 'ulfk');
Insert into maps values(330, 'AntonA');
Insert into maps values(332, 'leifericf');
Insert into maps values(333, 'Armor Mannekijns');
Insert into maps values(33333, 'Roaming test');
Insert into maps values(334, 'Social Mannekijns');
Insert into maps values(335, 'Weapon Mannekijns');
Insert into maps values(336, 'Player buildings');
Insert into maps values(337, 'Head Test Playfield');
Insert into maps values(338, 'Knut hizhouse');
Insert into maps values(34, 'Joeh/Einar');
Insert into maps values(340, 'Oyvind Berget');
Insert into maps values(350, 'Coder Effect Test Playfield');
Insert into maps values(351, 'mons playfield');
Insert into maps values(37, 'lees_villa_test');
Insert into maps values(38, 'Tim Donks Test Playfield');
Insert into maps values(381, 'Field of the Dead - Camps 20 21 etc');
Insert into maps values(39, 'Ketil''s combat fields');
Insert into maps values(4, 'Mariannek_test_playfield');
Insert into maps values(40, 'TrapTest');
Insert into maps values(4000, 'Stygian Galley');
Insert into maps values(4001, 'GalleyBackup');
Insert into maps values(4002, 'Stygian Galley - The Escape');
Insert into maps values(4010, 'Tortage Island');
Insert into maps values(4015, 'Tortage Volcano');
Insert into maps values(4020, 'City of Tortage');
Insert into maps values(4022, 'City of Tortage Night');
Insert into maps values(4023, 'Tortage Town Rui Nadini Spawn Test');
Insert into maps values(4025, 'Acheronian Ruins');
Insert into maps values(4026, 'Preparation Chamber');
Insert into maps values(4027, 'Acheronian Ruins Backside');
Insert into maps values(404, 'Dags Combat: PatrolTest');
Insert into maps values(4040, 'Tortage Root');
Insert into maps values(4041, 'Tortage Root Clone');
Insert into maps values(4043, 'BU02 Tortage Root - last pangea');
Insert into maps values(405, 'Area 51');
Insert into maps values(406, 'Hugo''s test');
Insert into maps values(407, 'GTA');
Insert into maps values(4086, 'Khopshef Video 8-22-2006');
Insert into maps values(410, 'Ruic Boot Camp');
Insert into maps values(411, 'Russian Fashion Playfield');
Insert into maps values(413, 'InstanceTest.B1');
Insert into maps values(414, 'InstanceTest.B2');
Insert into maps values(415, 'InstanceTest.B3');
Insert into maps values(42, 'Jespers Test');
Insert into maps values(43, 'Jesper ACG Test');
Insert into maps values(44, 'Einarf - General Tests');
Insert into maps values(44446, 'Atzel''s Fortress frozen river WIP');
Insert into maps values(44447, 'markuss testfield');
Insert into maps values(44448, 'markuss test2');
Insert into maps values(44449, 'SerkPlayfield');
Insert into maps values(44450, 'Atzel''s Fortress');
Insert into maps values(44460, 'Black Ring Citadel');
Insert into maps values(45, 'TestPlayfield');
Insert into maps values(4522, 'Room 9  ');
Insert into maps values(4533, 'Thirsty Dog Inn');
Insert into maps values(4534, 'Thirsty Dog Inn');
Insert into maps values(4555, 'Ulric`s Mansion');
Insert into maps values(4556, 'Ghost Palace');
Insert into maps values(4557, 'Mithrelle''s Mansion');
Insert into maps values(4558, 'Den Of No Return');
Insert into maps values(4559, 'Tina''s Room');
Insert into maps values(4560, 'Tortage Keep - Motherplayfield');
Insert into maps values(4561, 'Tortage Keep - Rogue');
Insert into maps values(4562, 'Tortage Keep - Mage');
Insert into maps values(4563, 'Tortage Keep - Warrior');
Insert into maps values(4564, 'Tortage Keep - Priest');
Insert into maps values(4565, 'Mausoleum');
Insert into maps values(4569, 'Tortage Underhalls Day');
Insert into maps values(4570, 'Tortage Underhalls Night');
Insert into maps values(4571, 'Raboz''s Cell');
Insert into maps values(4572, 'Renton''s House');
Insert into maps values(4573, 'Atlantean Cave');
Insert into maps values(4574, 'Coastal Cave');
Insert into maps values(4576, 'Genzio''s House');
Insert into maps values(4577, 'Seadog House');
Insert into maps values(4578, 'The ship the Tiamat');
Insert into maps values(4579, 'Abandoned Warehouse');
Insert into maps values(4580, 'Bartholomo Shop');
Insert into maps values(4581, 'Tarisha''s Shop');
Insert into maps values(4582, 'Renton''s House');
Insert into maps values(4590, 'Bartholomo Shop Night');
Insert into maps values(47, 'Resurrection Test');
Insert into maps values(5, 'LorenzoA Test Ground');
Insert into maps values(500, 'GM Island');
Insert into maps values(5000, 'Cragsfell - Border Kingdoms');
Insert into maps values(5002, 'Totem Torrent');
Insert into maps values(5003, 'PvP - TEAM DEATHMATCH');
Insert into maps values(5005, 'Hallowed Vaults');
Insert into maps values(5010, 'Dark Cathedral');
Insert into maps values(5011, 'Courtyard');
Insert into maps values(5012, 'Lost Temple');
Insert into maps values(505, 'Khopshef Province Heigh_Tiles_Statels');
Insert into maps values(506, 'Border Range statel_height_paint');
Insert into maps values(507, 'Wild Lands of Zelata_statel_height_painting');
Insert into maps values(508, 'Conall''s Valley Heigh_Tiles_Statels');
Insert into maps values(50869, 'White Sands_NEW_AUDIO');
Insert into maps values(50870, 'Khopshef Province_NEW_AUDIO');
Insert into maps values(50871, 'Wild Lands of Zelata_NEW_AUDIO');
Insert into maps values(510, 'SerkanS Test');
Insert into maps values(5100, 'Border Kingdoms - Massive PvP');
Insert into maps values(5200, 'PvP CTF 1');
Insert into maps values(5201, 'Blood Ravine');
Insert into maps values(54, 'Hiving Heaven');
Insert into maps values(55, 'Christoffer County');
Insert into maps values(57, 'Ole Jorgen Beaver Horde Plains');
Insert into maps values(58, 'Lush LOD Lake');
Insert into maps values(6001, 'Timmy');
Insert into maps values(606, 'GiantKing_temporary');
Insert into maps values(61, 'Idars Happy place');
Insert into maps values(62, 'Martin''s PF');
Insert into maps values(63, 'The Zoo');
Insert into maps values(65, 'New Scry Test');
Insert into maps values(66, 'Sergey_Test');
Insert into maps values(67, 'Water Test');
Insert into maps values(68, 'SergeyTest2');
Insert into maps values(70, 'Eirik Munthe');
Insert into maps values(700, 'empty 1k x 1k');
Insert into maps values(701, 'Hiving_TestField_One_Building');
Insert into maps values(702, 'Hiving_Test_Field_Multiple_Buildings');
Insert into maps values(78, 'Speedtree test');
Insert into maps values(8, 'shank');
Insert into maps values(80, 'Camera test level');
Insert into maps values(801, 'Secret World');
Insert into maps values(802, 'secret test 2');
Insert into maps values(81, 'Oysteins secret place');
Insert into maps values(810, 'Richs test');
Insert into maps values(815, 'Kjetils Test');
Insert into maps values(82, 'Rui - HIVE testing');
Insert into maps values(820, 'testlevel_oyvind');
Insert into maps values(83, 'Leifs testcase pf');
Insert into maps values(850, 'playerbuilt buildings ');
Insert into maps values(87, 'JarleN test PF');
Insert into maps values(88, 'Rui obstical course');
Insert into maps values(89, 'Massive Pvp Test');
Insert into maps values(9, 'Davids Test Playplace');
Insert into maps values(905, 'Paralax_Test');
Insert into maps values(906, 'Flat');
Insert into maps values(91, 'Andrew''s Playfield');
Insert into maps values(910, 'Simon''s Test PF');
Insert into maps values(916, 'Blood Ravine - FPS BENCHMARK');
Insert into maps values(917, 'Tortage Town - FPS test');
Insert into maps values(93, 'Heid''s Playground');
Insert into maps values(930, 'Audio: Fixed3D, footsteps, BA, Reverb');
Insert into maps values(932, 'Audio: Weather systems');
Insert into maps values(933, 'Tords lekeplass');
Insert into maps values(934, 'World Design - Audio Properties');
Insert into maps values(935, 'Test - Time_of_Day & Weather - AUDIO');
Insert into maps values(936, 'Conarch Village - RIVERS');
Insert into maps values(937, 'Conall''s Valley - AUDIO RIVERS');
Insert into maps values(938, 'Bubshur House - RIVERS_AUDIO');
Insert into maps values(939, 'Wild Lands of Zelata_statel_height_painting_RIVERS AUDIO');
Insert into maps values(940, 'Audio Town');
Insert into maps values(941, 'Blessed Caves - RIVERS_AUDIO');
Insert into maps values(942, 'Tortage Town - RIVERS_AUDIO');
Insert into maps values(943, 'Sanctum of the Burning Souls - RIVERS_AUDIO');
Insert into maps values(944, 'Tortage Island - RIVERS_AUDIO');
Insert into maps values(945, 'Tortage Volcano - RIVERS_AUDIO');
Insert into maps values(946, 'Acheronian Ruins - RIVERS_AUDIO');
Insert into maps values(948, 'Imirian Ravine - RIVERS_AUDIO');
Insert into maps values(949, 'The Onyx Chambers - RIVERS_AUDIO');
Insert into maps values(95, 'Mojo''s playground');
Insert into maps values(950, 'Os Harku_sound_playfied');
Insert into maps values(951, 'Lacheish Plains - RIVERS_AUDIO');
Insert into maps values(952, 'Poitain - RIVERS_AUDIO');
Insert into maps values(953, 'Field of the Dead - RIVERS_AUDIO');
Insert into maps values(954, 'Tarantia Noble District - RIVERS_AUDIO');
Insert into maps values(955, 'The Main System - RIVERS_AUDIO');
Insert into maps values(956, 'Purple Lotus Swamp - RIVERS_AUDIO');
Insert into maps values(957, 'The Main System . RIVERS_AUDIO-v2');
Insert into maps values(958, 'Outflow Tunnels - RIVERS_AUDIO');
Insert into maps values(96, 'Evan''s New Magical PF');
Insert into maps values(960, 'Field of the Dead - RIVERS_AUDIO_v2');
Insert into maps values(961, 'Conall''s Valley - RIVERS_AUDIO_v2');
Insert into maps values(962, 'Tarantia Noble District - RIVERS_AUDIO_v2');
Insert into maps values(963, 'Tortage Underhalls Day - RIVERS_AUDIO');
Insert into maps values(964, 'Tortage Underhalls Night - RIVERS_AUDIO');
Insert into maps values(965, 'Old Tarantia - RIVERS_AUDIO');
Insert into maps values(99, 'Andreaso''s Playfield');
Insert into maps values(999, 'Helens Quest Dungeon');